name: Create production builds

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android production app-bundle
    type: build
    params:
      platform: android
      profile: production
